#!/bin/bash

if [ -d build ]; then rm -rf build; fi;
mkdir build
g++ -std=c++11 -c src/series_summer.cpp -o build/series_summer.o
g++ -std=c++11 -c src/nilakantha.cpp -o build/nilakantha.o
g++ -std=c++11 build/series_summer.o build/nilakantha.o -o nilakantha
